// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: authorization_codes.sql

package query

import (
	"context"
	"time"
)

const deleteAuthorizationCode = `-- name: DeleteAuthorizationCode :one
delete from authorization_codes
where id = $1
returning id, client_id, user_id, scopes, expires, created, updated
`

func (q *Queries) DeleteAuthorizationCode(ctx context.Context, id string) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, deleteAuthorizationCode, id)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.Expires,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertAuthorizationCode = `-- name: InsertAuthorizationCode :exec
insert into authorization_codes (
    id
    , user_id
    , client_id
    , scopes
    , expires
) values (
     $1
     , $2
     , $3
     , $4
     , $5
 )
`

type InsertAuthorizationCodeParams struct {
	ID       string
	UserID   string
	ClientID string
	Scopes   []string
	Expires  time.Time
}

func (q *Queries) InsertAuthorizationCode(ctx context.Context, arg InsertAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, insertAuthorizationCode,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.Expires,
	)
	return err
}

const selectAuthorizationCode = `-- name: SelectAuthorizationCode :one
select id, client_id, user_id, scopes, expires, created, updated
from authorization_codes
where id = $1
`

func (q *Queries) SelectAuthorizationCode(ctx context.Context, id string) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, selectAuthorizationCode, id)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.Expires,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
