// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: clients.sql

package query

import (
	"context"
)

const selectClient = `-- name: SelectClient :one
select id, secret, suspended, name, created, updated
from clients
where id = $1
`

func (q *Queries) SelectClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, selectClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Secret,
		&i.Suspended,
		&i.Name,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
