// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package query

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID           string
	ClientID     string
	RefreshToken string
	UserID       string
	Scopes       []string
	Expires      time.Time
	Revoked      bool
	Created      time.Time
	Updated      time.Time
}

type AuthorizationCode struct {
	ID       string
	ClientID string
	UserID   string
	Scopes   []string
	Expires  time.Time
	Created  time.Time
	Updated  time.Time
}

type Client struct {
	ID        string
	Suspended bool
	Created   time.Time
	Updated   time.Time
}

type RefreshToken struct {
	ID       string
	ClientID string
	UserID   string
	Scopes   []string
	Expires  time.Time
	Revoked  bool
	Created  time.Time
	Updated  time.Time
}

type Scope struct {
	ID          string
	Description sql.NullString
	Created     time.Time
	Updated     time.Time
}
