// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package query

import (
	"database/sql"
	"time"
)

type AuthorizationCode struct {
	ID        string
	UserID    string
	Scopes    []string
	Expires   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Client struct {
	ID        string
	Suspended bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Scope struct {
	ID          string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
